on:
  pull_request:
    branches: [main]
    paths:
      - "TP4/**"
      - ".github/workflows/build.yml"
    

permissions:
  contents: read
  actions: write
  pull-requests: write
  checks: write

jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
      - name: Install Ceedling
        run: gem install ceedling -v 1.0.1
      - name: install GCov Report
        run: |
          sudo apt-get install lcov gcovr
          pip install gcovr
      - name: Run Unit Tests
        run: cd TP4 && ceedling clobber gcov:all
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Ceedling uNit Tests
          path: TP4/build/artifacts/gcov/junit_tests_report.xml
          reporter: jest-junit
      - name: Code Coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: TP4/build/artifacts/gcov/GcovCoverageCobertura.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: "60 80"
      - name: Output to Job Summary
        run: cat code-coverage-result.md >> $GITHUB_STEP_SUMMARY
      - name: Add Coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-result.md
      